// Builds worker/src/facts.js — the only knowledge Ronie's chat model gets — from js/data.js.
// Run after editing data.js:  node tools/ronie-facts.mjs   (then redeploy the worker)
import fs from 'node:fs';
import vm from 'node:vm';

const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(new URL('../js/data.js', import.meta.url), 'utf8'), ctx);
const D = ctx.window.PORTFOLIO;
const A = D.assistant;

const lines = [];
const add = (s = '') => lines.push(s);
const clean = (s) => String(s).replace(/\{[a-z]+\}/gi, 'you').replace(/\s+/g, ' ').trim();

add(`Name: ${D.name}`);
add(`Summary: ${clean(D.bio)}`);
add(`Email: ${A.email}`);
add(`Links: ${D.links.map((l) => `${l.label}: ${l.href.replace('mailto:', '')}`).join(' | ')}`);
add(`Time spent in AI/ML: ${D.time.hours}+ hours since ${D.time.start.year} (started in ${D.time.start.city}, now in ${D.time.end.city}).`);
add();
add('Experience and education (oldest first):');
for (const e of D.experience) add(`- ${e.years}: ${clean(e.org)} — ${clean(e.role)} (${e.place})`);
add();
add('Skills (with tools):');
for (const s of D.skills.items) add(`- ${s.name}: ${s.tools.join(', ')}`);
add();
add('Projects:');
for (const p of D.projects) add(`- ${p.title} (${p.year}, ${p.category}): ${clean(p.description)} Tech: ${p.tags.join(', ')}.${p.link && p.link !== '#' ? ` Link: ${p.link}` : ''}`);
add();
add('Case studies from his work:');
for (const c of D.caseStudies) add(`- ${c.title} (${c.year}): ${clean(c.description)}`);
add();
add('Certifications:');
for (const c of D.certifications) add(`- ${c.title} — ${c.issuer}, ${c.date}`);
if (D.profile && D.profile.traits) {
  add();
  add('About him:');
  for (const t of D.profile.traits) add(`- ${t.title} (in his own words): ${clean(t.text)}`);
}
// the scripted story Ronie already tells (journey, what he builds, how he works, fun facts)
const story = Object.entries(A.steps)
  .filter(([id]) => /^(journey|builds|works|facts)-/.test(id))
  .map(([, s]) => clean([].concat(s.say || [])[0] || ''))
  .filter(Boolean);
if (story.length) {
  add();
  add('Things Ronie already says about him:');
  for (const s of story) add(`- ${s}`);
}

add();
add('Glossary (use these exact meanings): RAG = retrieval-augmented generation; LLM = large language model; RLHF = reinforcement learning from human feedback; NLP = natural language processing; MARL = multi-agent reinforcement learning; ML = machine learning; ATS = applicant tracking system; SHAP = SHapley Additive exPlanations; DIAT = Defence Institute of Advanced Technology; QA = quality assurance.');

const out = `// Generated by tools/ronie-facts.mjs from js/data.js — do not edit by hand.\nexport const FACTS = ${JSON.stringify(lines.join('\n'))};\n`;
fs.mkdirSync(new URL('../worker/src/', import.meta.url), { recursive: true });
fs.writeFileSync(new URL('../worker/src/facts.js', import.meta.url), out);
console.log(`worker/src/facts.js: ${lines.length} lines, ${out.length} chars`);
